Repository sundowndev/TasteHealthy, pull requests merged in 2019-05, with the labels that each got.

#12 [Feature] API docker image
  .dockerignore
  docker-compose.yml
  server/Dockerfile
Labels: api, enhancement

#14 Feature: Client architecture
  client/__mocks__/styleMock.js
  client/app/components/modal.js
  client/app/containers/HomePage/index.js
  client/app/containers/MealsPage/index.js
  client/app/containers/MealsPage/tests/__snapshots__/index.test.js.snap
  client/app/styles/index.css
  client/app/styles/index.scss
  package-lock.json
  package.json
Labels: enhancement

#15 Handle arguments in API Dockerfile
  docker-compose.yml
  server/Dockerfile
Labels: api, enhancement

#17 API improvements
  scripts/populate.js
  server/app/db/models/index.js
  server/app/db/models/misc_data.js
  server/app/db/models/nutrition_facts.js
  server/app/db/models/products.js
  server/app/routes/products/get.js
  server/test/routes/products/get.spec.js
Labels: api, enhancement

#20 v1.0.0rc2 merge
  LICENSE
  README.md
  package.json
Labels: api, client
